### ISSUE TITLE
我在sdcs_final下启动docker会报错

### ISSUE THREAD

**Issue by Shawnyyt** [Skyink/simple-distributed-cache-system#1]
node0-1  | Traceback (most recent call last):
node0-1  |   File "/usr/local/bin/flask", line 8, in <module>
node0-1  |     sys.exit(main())
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 1064, in main
node0-1  |     cli.main()
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
node0-1  |     rv = self.invoke(ctx)
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1682, in invoke
node0-1  |     cmd_name, cmd, args = self.resolve_command(ctx, args)
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1729, in resolve_command
node0-1  |     cmd = self.get_command(ctx, cmd_name)
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 566, in get_command
node0-1  |     self._load_plugin_commands()
node0-1  |   File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 558, in _load_plugin_commands
node0-1  |     import importlib_metadata as metadata
node0-1  | ModuleNotFoundError: No module named 'importlib_metadata'
三个node都会报错，我在requirements.txt中加入'importlib_metadata'也还是报错，请问怎么解决呢

**Comment by Skyink** [comment]
这是来自陈天白设置的自动回复邮件。

您好，您的邮件我已收到，我会尽快处理您的消息。谢谢~~祝好，一切顺利！

**Comment by Shawnyyt** [comment]
已解决
